# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 08:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import kernel.constructors.action
import kernel.constructors.permalink
import kernel.constructors.serializer
import kernel.constructors.uri
import kernel.constructors.views
import kernel.utils
import stdimage.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='KernelUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(default=uuid.uuid4, editable=False, max_length=120, verbose_name='Внешний ключ')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Изменен')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(db_index=True, max_length=255, unique=True, verbose_name='email')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='Фамилия')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='Имя')),
                ('middle_name', models.CharField(blank=True, max_length=30, verbose_name='Отчество')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Телефон')),
                ('date_birth', models.DateField(blank=True, null=True)),
                ('birth_int', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('is_emailing', models.BooleanField(default=True, verbose_name='Is emailing')),
                ('photo', stdimage.models.StdImageField(blank=True, upload_to=kernel.utils.upload_dir)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_kernel.kerneluser_set+', to='contenttypes.ContentType')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'пользователи',
                'verbose_name_plural': 'пользователи',
                'db_table': 'krn_user',
                'ordering': ['-last_name'],
                'swappable': 'AUTH_USER_MODEL',
            },
            bases=(kernel.constructors.action.ActionKernelModel, kernel.constructors.permalink.KernelPermalinkModel, kernel.constructors.views.KernelViewsModel, kernel.constructors.serializer.KernelSerializerModel, kernel.constructors.uri.KernelUriModel, models.Model),
        ),
    ]
