# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-06-01 09:45
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('kernel', '0003_auto_20160719_1702'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kerneluser',
            options={'ordering': ['-last_name'], 'verbose_name': 'пользователи', 'verbose_name_plural': 'пользователи'},
        ),
        migrations.AddField(
            model_name='kerneluser',
            name='birth_int',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='kerneluser',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='kerneluser',
            name='external_id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=120, verbose_name='Внешний ключ'),
        ),
        migrations.AlterField(
            model_name='kerneluser',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Изменен'),
        ),
    ]
