# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-06-01 12:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kernel', '0004_auto_20170601_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='kerneluser',
            name='is_emailing',
            field=models.BooleanField(default=True, verbose_name='Is emailing'),
        ),
    ]
